# Heuristics
CONST_H_NF      = "NF"
CONST_H_CPLEX   = "CPLEX"
CONST_H_FF      = "FF"
CONST_H_BFR     = "BFR"
CONST_H_BFD     = "BFD"
CONST_H_BFRTD   = "BFRTD"
CONST_H_FMF     = "FMF"
CONST_H_FMFF    = "FMFF"
CONST_H_FMFFTid = "FMFFTid"

CONST_H_myFF    = "myFF"
CONST_H_myBFR   = "myBFR"
CONST_H_myBFD   = "myBFD"
CONST_H_myNF    = "myNF"
CONST_H_mySS    = "mySS"
CONST_H_myWF    = "myWF"
CONST_H_myMRD   = "myMRD"
CONST_H_myMRR   = "myMRR"
CONST_H_myHA    = "myHA"

CONST_H_myFF_CPLEX  = "myFF_CPLEX"
CONST_H_myBFR_CPLEX = "myBFR_CPLEX"
CONST_H_myBFD_CPLEX = "myBFD_CPLEX"
CONST_H_myNF_CPLEX  = "myNF_CPLEX"
CONST_H_FMF_CPLEX   = "FMF_CPLEX"
CONST_H_myMRD_CPLEX = "myMRD_CPLEX"
CONST_H_myMRR_CPLEX = "myMRR_CPLEX"
CONST_H_mySS_CPLEX  = "mySS_CPLEX"
CONST_H_myHA_CPLEX  = "myHA_CPLEX"


CONST_H_SOLVERS = [
    CONST_H_NF,
    CONST_H_FF,
    CONST_H_BFR,
    CONST_H_BFD,
    CONST_H_FMF,
    CONST_H_FMFF,
    CONST_H_FMFFTid,
    CONST_H_CPLEX,
    CONST_H_mySS,
    CONST_H_myWF,
    CONST_H_myMRD,
    CONST_H_myMRR,
    CONST_H_myHA
    ]

CONST_NOPLOT_TW0 = [
    CONST_H_FMF,
    CONST_H_FMF_CPLEX,
    CONST_H_myFF_CPLEX,
    CONST_H_myBFR_CPLEX,
    CONST_H_myBFD_CPLEX,
    CONST_H_myNF_CPLEX,
    CONST_H_myMRD_CPLEX,
    CONST_H_myMRR_CPLEX,
    CONST_H_mySS_CPLEX, 
    CONST_H_myHA_CPLEX
    ]

# Ordering
CONST_O_LIST = "LIST"
CONST_O_RAND = "RAND"
CONST_O_DREQ = "DREQ"
CONST_O_DDUR = "DDUR"
CONST_O_DDTR = "DDTR"

#CONST_ORDERINGS = [
    #CONST_O_LIST,
    #CONST_O_RAND,
    #CONST_O_DREQ,
    #CONST_O_DDUR,
    #CONST_O_DDTR
    #]

CONST_ORDERINGS = [
    CONST_O_LIST,
    CONST_O_DDUR
    ]

CONST_F_IN    = "FIN"
CONST_F_SOL   = "FSOL"
CONST_F_USAGE = "FUSA"
CONST_F_LB    = "FLB"
CONST_F_TIME  = "FTIME"
CONST_F_CPLEX = "FCPLEX"
CONST_F_CPFMF = "FCPFMF"
CONST_F_TMP   = "tmp"

CONST_SECINMILISEC = 1000000
CONST_NUMIMPREC    = 0.00001
CONST_MAX_TCUTOFF  = 12000
CONST_UNIT = 1.0
CONST_LCPU = 'cpu'
CONST_LRAM = 'ram'
